# Generated by Django 4.0.4 on 2022-09-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='connected_user',
        ),
    ]
