# Generated by Django 4.0.4 on 2022-09-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0004_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='description',
            new_name='details',
        ),
    ]
