# Generated by Django 4.0.4 on 2022-09-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0005_rename_description_query_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='picture_song_name',
        ),
        migrations.AddField(
            model_name='query',
            name='picture_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mypics.picture'),
        ),
        migrations.AlterField(
            model_name='query',
            name='offending_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mypics.profile'),
        ),
        migrations.AlterField(
            model_name='query',
            name='user_filing_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mypics.profile'),
        ),
    ]
