# Generated by Django 4.0.4 on 2022-09-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0006_remove_query_picture_song_name_query_picture_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='song_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mypics.picture'),
        ),
        migrations.AlterField(
            model_name='query',
            name='offending_user',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='query',
            name='picture_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mypics.picture'),
        ),
        migrations.AlterField(
            model_name='query',
            name='user_filing_complaint',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
