# Generated by Django 4.0.4 on 2022-09-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0007_query_song_name_alter_query_offending_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='picture_name',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='query',
            name='song_name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
