# Generated by Django 4.0.4 on 2022-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0008_alter_query_picture_name_alter_query_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='picture_name',
            field=models.CharField(blank=True, default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='query',
            name='song_name',
            field=models.CharField(blank=True, default=None, max_length=120),
        ),
    ]
