# Generated by Django 4.0.4 on 2022-09-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0009_alter_query_picture_name_alter_query_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='details',
            field=models.TextField(default=None),
        ),
    ]
