# Generated by Django 4.0.4 on 2022-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0015_alter_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_url',
            field=models.CharField(blank=True, default='https://www.google.com', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_url',
            field=models.CharField(blank=True, default='https://www.google.com', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_url',
            field=models.CharField(blank=True, default='https://www.google.com', max_length=120, null=True),
        ),
    ]
