# Generated by Django 4.0.4 on 2022-09-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0016_alter_profile_telegram_url_alter_profile_vk_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_url',
            field=models.CharField(blank=True, default='https://web.telegram.org/k/', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_url',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_url',
            field=models.CharField(blank=True, default='https://www.youtube.com', max_length=120, null=True),
        ),
    ]
