# Generated by Django 4.1 on 2022-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0017_alter_profile_telegram_url_alter_profile_vk_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
