# Generated by Django 4.0.4 on 2022-09-30 07:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0018_profile_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
